name: Node.js CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # Step 1: Clone the repository
    - uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

      # Step 3: Install dependencies from package-lock.json
    - name: Install dependencies
      run: npm ci

      # Step 4: Install stable version of Chrome
    - name: Install Chrome stable
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: 'stable'

      # Step 5: Install the latest version of ChromeDriver
    - name: Install latest ChromeDriver
      run: npm install chromedriver@latest

      # Step 6: Configure display for headless Chrome
    - name: Set up DISPLAY for headless
      run: echo "DISPLAY=:99" >> $GITHUB_ENV

      # Step 7: Run tests with CI environment settings
    - name: Run tests
      run: npm test
      env:
        FORCE_COLOR: 2  # Enable colored output for better readability
